version: "3"
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - elasticsearch
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - ES_HEAP_SIZE=256m
      - discovery.type=single-node
