name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.10.3"
          otp-version: "23.0.1"
      - name: Install Dependencies
        run: mix deps.get
      - name: Run formatter
        run: mix format --check-formatted
