name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  ELIXIR_VERSION: "1.10.3"
  OTP_VERSION: "23.0.1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{env.ELIXIR_VERSION}}
          otp-version: ${{env.OTP_VERSION}}
      - name: Install Dependencies
        run: mix deps.get
      - name: Run formatter
        run: mix format --check-formatted
      - name: Run Credo
        run: mix credo
