name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  ELIXIR_VERSION: "1.10.3"
  OTP_VERSION: "23.0.1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{env.ELIXIR_VERSION}}
          otp-version: ${{env.OTP_VERSION}}
      - name: Install Dependencies
        run: mix deps.get
      - uses: actions/cache@v2
        with:
          path: build
          key: build-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            build-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-
      - name: Run formatter
        run: mix format --check-formatted
      - name: Run Credo
        run: mix credo
      - uses: actions/cache@v2
        with:
          path: _build/dev/dialyzer_erlang-${{env.OTP_VERSION}}_elixir-${{env.ELIXIR_VERSION}}_deps-dev.plt
          key: dialyzer-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            dialyzer-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-
      - name: Run dialyzer
        run: mix dialyzer
